// <auto-generated />
namespace Mis333ksp18Group17.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _23u324y1iu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_23u324y1iu));
        
        string IMigrationMetadata.Id
        {
            get { return "201804261618248_23u324y1iu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
