// <auto-generated />
namespace Mis333ksp18Group17.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _83t528743 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_83t528743));
        
        string IMigrationMetadata.Id
        {
            get { return "201804290451057_83t528743"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
