// <auto-generated />
namespace Mis333ksp18Group17.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sjkfahkja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sjkfahkja));
        
        string IMigrationMetadata.Id
        {
            get { return "201804270258130_sjkfahkja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
